version: "3.9"

services:
  node_app:
    container_name: node_app
    build: .
    image: hyulio/node_live_app
    ports:
      - "3000:3000"
    environment:
      - POSTGRESDB=node_live_db
      - POSTGRESUSER=hyulio
      - POSTGRESPASSWORD=12345
      - POSTGRESHOST=node_db
    depends_on:
      - node_db

  node_db:
    container_name: node_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=node_live_db
      - POSTGRES_USER=hyulio
      - POSTGRES_PASSWORD=12345
    volumes:
      - node_db_data:/var/lib/postgresql/data

volumes:
  node_db_data: {}